/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "fsm_handshake" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fsm_handshake/design/src/fsm_handshake.v:3.1-52.10" *)
module fsm_handshake(clk, rst_n, start, done, busy, valid);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fsm_handshake/design/src/fsm_handshake.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fsm_handshake/design/src/fsm_handshake.v:5.11-5.16" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fsm_handshake/design/src/fsm_handshake.v:6.11-6.16" *)
  input start;
  wire start;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fsm_handshake/design/src/fsm_handshake.v:7.11-7.15" *)
  input done;
  wire done;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fsm_handshake/design/src/fsm_handshake.v:8.16-8.20" *)
  output busy;
  wire busy;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fsm_handshake/design/src/fsm_handshake.v:9.16-9.21" *)
  output valid;
  wire valid;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire \state_q[0] ;
  sky130_fd_sc_hd__inv_1 _06_ (
    .A(start),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a21o_1 _07_ (
    .A1(_05_),
    .A2(\state_q[0] ),
    .B1(valid),
    .X(_01_)
  );
  sky130_fd_sc_hd__inv_1 _08_ (
    .A(busy),
    .Y(_03_)
  );
  sky130_fd_sc_hd__nand2_1 _09_ (
    .A(start),
    .B(\state_q[0] ),
    .Y(_04_)
  );
  sky130_fd_sc_hd__o21ai_1 _10_ (
    .A1(_03_),
    .A2(done),
    .B1(_04_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__and2_1 _11_ (
    .A(busy),
    .B(done),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfstp_2 \state_q[0]$_DFF_PN1_  (
    .CLK(clk),
    .D(_01_),
    .Q(\state_q[0] ),
    .SET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \state_q[1]$_DFF_PN0_  (
    .CLK(clk),
    .D(_00_),
    .Q(valid),
    .RESET_B(rst_n)
  );
  sky130_fd_sc_hd__dfrtp_1 \state_q[2]$_DFF_PN0_  (
    .CLK(clk),
    .D(_02_),
    .Q(busy),
    .RESET_B(rst_n)
  );
endmodule
