// Generated by Spec-to-RTL pipeline: grammar -> IR -> RTL
// auto-wrapped combinational/spec-only logic for clocked OpenROAD flow

module alu8 (
    input clk,
    input reset,
    input [7:0] a,
    input [7:0] b,
    input [2:0] op,
    output reg [7:0] y
);

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            y <= 0;
        end else begin
            if (op == 0) begin
                y <= a + b;
            end
            if (op == 1) begin
                y <= a - b;
            end
            if (op == 2) begin
                y <= a & b;
            end
            if (op == 3) begin
                y <= a | b;
            end
            if (op == 4) begin
                y <= a ^ b;
            end
            if (op == 5) begin
                y <= a << 1;
            end
            if (op == 6) begin
                y <= a >> 1;
            end
            if (op == 7) begin
                y <= 0;
            end
        end
    end

endmodule
