// Generated by Spec-to-RTL pipeline: grammar -> IR -> RTL
// Repair demo setup: injected an output bug that forces y to zero

module comb_adder8 (
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] y
);

    always @* begin
        y = a + b;
    end

endmodule
