// Generated by Spec-to-RTL pipeline: grammar -> IR -> RTL
// Repair demo setup: injected an output bug that forces flag to zero

module pulse_latch (
    input clk,
    input rst_n,
    input set_pulse,
    output reg flag
);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            flag <= 0;
        end else begin
            flag <= flag | set_pulse;
        end
    end

endmodule
