// Generated by Spec-to-RTL pipeline: grammar -> IR -> RTL
// Detects a binary sequence "0011" in the input stream.
// auto-wrapped combinational/spec-only logic for clocked OpenROAD flow

module seq_detector_0011 (
    input clk,
    input reset,
    input data_in,
    output reg detected
);

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            detected <= 0;
        end else begin
            detected <= detected;
        end
    end

endmodule
