// Generated by Spec-to-RTL pipeline: grammar -> IR -> RTL
// auto-wrapped combinational/spec-only logic for clocked OpenROAD flow

module updown_counter16 (
    input clk,
    input reset,
    input up,
    output reg [15:0] count
);

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            count <= 0;
        end else begin
            if (up == 1) begin
                count <= count + 1;
            end else begin
                count <= count - 1;
            end
        end
    end

endmodule
