/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "shift_left4" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:3.1-21.10" *)
module shift_left4(clk, rst_n, en, serial_in, shreg);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:5.11-5.16" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:6.11-6.13" *)
  input en;
  wire en;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:7.11-7.20" *)
  input serial_in;
  wire serial_in;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:8.22-8.27" *)
  output [3:0] shreg;
  wire [3:0] shreg;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  sky130_fd_sc_hd__mux2_2 _4_ (
    .A0(shreg[2]),
    .A1(shreg[1]),
    .S(en),
    .X(_0_)
  );
  sky130_fd_sc_hd__mux2_2 _5_ (
    .A0(shreg[0]),
    .A1(serial_in),
    .S(en),
    .X(_1_)
  );
  sky130_fd_sc_hd__mux2_2 _6_ (
    .A0(shreg[3]),
    .A1(shreg[2]),
    .S(en),
    .X(_2_)
  );
  sky130_fd_sc_hd__mux2_2 _7_ (
    .A0(shreg[1]),
    .A1(shreg[0]),
    .S(en),
    .X(_3_)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \shreg[0]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_1_),
    .Q(shreg[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \shreg[1]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_3_),
    .Q(shreg[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \shreg[2]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_0_),
    .Q(shreg[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/shift_left4/design/src/shift_left4.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \shreg[3]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_2_),
    .Q(shreg[3]),
    .RESET_B(rst_n)
  );
endmodule
