/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "register8" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:3.1-21.10" *)
module register8(clk, rst_n, en, d, q);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:5.11-5.16" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:6.11-6.13" *)
  input en;
  wire en;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:7.17-7.18" *)
  input [7:0] d;
  wire [7:0] d;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:8.22-8.23" *)
  output [7:0] q;
  wire [7:0] q;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  sky130_fd_sc_hd__buf_6 _09_ (
    .A(en),
    .X(_08_)
  );
  sky130_fd_sc_hd__mux2_4 _10_ (
    .A0(q[6]),
    .A1(d[6]),
    .S(_08_),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_4 _11_ (
    .A0(q[4]),
    .A1(d[4]),
    .S(_08_),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_4 _12_ (
    .A0(q[3]),
    .A1(d[3]),
    .S(_08_),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_4 _13_ (
    .A0(q[2]),
    .A1(d[2]),
    .S(_08_),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_4 _14_ (
    .A0(q[1]),
    .A1(d[1]),
    .S(_08_),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_4 _15_ (
    .A0(q[0]),
    .A1(d[0]),
    .S(_08_),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_4 _16_ (
    .A0(q[7]),
    .A1(d[7]),
    .S(_08_),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_4 _17_ (
    .A0(q[5]),
    .A1(d[5]),
    .S(_08_),
    .X(_07_)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \q[0]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_05_),
    .Q(q[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \q[1]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_04_),
    .Q(q[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \q[2]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_03_),
    .Q(q[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \q[3]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_02_),
    .Q(q[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \q[4]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_01_),
    .Q(q[4]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \q[5]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_07_),
    .Q(q[5]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \q[6]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_00_),
    .Q(q[6]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/register8/design/src/register8.v:11.5-19.8" *)
  sky130_fd_sc_hd__dfrtp_1 \q[7]$_DFFE_PN0P_  (
    .CLK(clk),
    .D(_06_),
    .Q(q[7]),
    .RESET_B(rst_n)
  );
endmodule
