/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "exp_fixed_point" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/exp_fixed_point/design/src/exp_fixed_point.v:4.1-20.10" *)
module exp_fixed_point(clk, rst, enable, x_in, exp_out);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/exp_fixed_point/design/src/exp_fixed_point.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/exp_fixed_point/design/src/exp_fixed_point.v:6.11-6.14" *)
  input rst;
  wire rst;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/exp_fixed_point/design/src/exp_fixed_point.v:7.11-7.17" *)
  input enable;
  wire enable;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/exp_fixed_point/design/src/exp_fixed_point.v:8.11-8.15" *)
  input x_in;
  wire x_in;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/exp_fixed_point/design/src/exp_fixed_point.v:9.16-9.23" *)
  output exp_out;
  wire exp_out;
  wire _0_;
  sky130_fd_sc_hd__conb_1 _1_ (
    .LO(_0_)
  );
  sky130_fd_sc_hd__buf_4 _2_ (
    .A(_0_),
    .X(exp_out)
  );
endmodule
