/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "sum_stage" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:3.1-23.10" *)
module sum_stage(clk, rst_n, in_valid, a, b, sum_out, valid);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:5.11-5.16" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:6.11-6.19" *)
  input in_valid;
  wire in_valid;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:7.17-7.18" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:8.17-8.18" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:9.22-9.29" *)
  output [8:0] sum_out;
  wire [8:0] sum_out;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:10.16-10.21" *)
  output valid;
  wire valid;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _00_;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _01_;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _02_;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _03_;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _04_;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _05_;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _06_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:6.31-6.32" *)
  wire _07_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _08_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _09_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _10_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _11_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _12_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _13_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _14_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:6.25-6.26" *)
  wire _15_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _16_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _17_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _18_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _19_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _20_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _21_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire _41_;
  wire _42_;
  wire _43_;
  wire _44_;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _45_;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:18.24-18.29|/home/sudar762/OpenROAD-flow-scripts/tools/install/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _46_;
  sky130_fd_sc_hd__a21oi_1 _47_ (
    .A1(_19_),
    .A2(_08_),
    .B1(_18_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nor2b_1 _48_ (
    .A(_23_),
    .B_N(_10_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__nand3_1 _49_ (
    .A(_21_),
    .B(_12_),
    .C(_09_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__a21oi_2 _50_ (
    .A1(_21_),
    .A2(_11_),
    .B1(_20_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__nand2_1 _51_ (
    .A(_25_),
    .B(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a31oi_1 _52_ (
    .A1(_21_),
    .A2(_12_),
    .A3(_24_),
    .B1(_27_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__nand2_1 _53_ (
    .A(_17_),
    .B(_14_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__a21oi_1 _54_ (
    .A1(_17_),
    .A2(_13_),
    .B1(_16_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__o21ai_0 _55_ (
    .A1(_28_),
    .A2(_29_),
    .B1(_30_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__nand2_1 _56_ (
    .A(_21_),
    .B(_12_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__a211oi_1 _57_ (
    .A1(_15_),
    .A2(_07_),
    .B1(_22_),
    .C1(_18_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__o21ai_0 _58_ (
    .A1(_19_),
    .A2(_18_),
    .B1(_10_),
    .Y(_33_)
  );
  sky130_fd_sc_hd__nor3_1 _59_ (
    .A(_31_),
    .B(_32_),
    .C(_33_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor2b_2 _60_ (
    .A(_17_),
    .B_N(_14_),
    .Y(_35_)
  );
  sky130_fd_sc_hd__inv_1 _61_ (
    .A(_17_),
    .Y(_36_)
  );
  sky130_fd_sc_hd__nor3_1 _62_ (
    .A(_36_),
    .B(_14_),
    .C(_13_),
    .Y(_37_)
  );
  sky130_fd_sc_hd__a221o_1 _63_ (
    .A1(_36_),
    .A2(_13_),
    .B1(_27_),
    .B2(_35_),
    .C1(_37_),
    .X(_38_)
  );
  sky130_fd_sc_hd__nor4_1 _64_ (
    .A(_36_),
    .B(_13_),
    .C(_27_),
    .D(_34_),
    .Y(_39_)
  );
  sky130_fd_sc_hd__a211o_1 _65_ (
    .A1(_34_),
    .A2(_35_),
    .B1(_38_),
    .C1(_39_),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _66_ (
    .A(_14_),
    .B(_28_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__o21bai_1 _67_ (
    .A1(_32_),
    .A2(_33_),
    .B1_N(_09_),
    .Y(_40_)
  );
  sky130_fd_sc_hd__a21oi_1 _68_ (
    .A1(_12_),
    .A2(_40_),
    .B1(_11_),
    .Y(_41_)
  );
  sky130_fd_sc_hd__xnor2_1 _69_ (
    .A(_21_),
    .B(_41_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor2_1 _70_ (
    .A(_09_),
    .B(_24_),
    .Y(_42_)
  );
  sky130_fd_sc_hd__xnor2_1 _71_ (
    .A(_12_),
    .B(_42_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__a21o_1 _72_ (
    .A1(_15_),
    .A2(_07_),
    .B1(_22_),
    .X(_43_)
  );
  sky130_fd_sc_hd__a21oi_1 _73_ (
    .A1(_19_),
    .A2(_43_),
    .B1(_18_),
    .Y(_44_)
  );
  sky130_fd_sc_hd__xnor2_1 _74_ (
    .A(_10_),
    .B(_44_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xor2_1 _75_ (
    .A(_19_),
    .B(_08_),
    .X(_01_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:42.31-44.12" *)
  sky130_fd_sc_hd__fa_1 _76_ (
    .A(a[1]),
    .B(b[1]),
    .CIN(_07_),
    .COUT(_08_),
    .SUM(_46_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _77_ (
    .A(a[3]),
    .B(b[3]),
    .COUT(_09_),
    .SUM(_10_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _78_ (
    .A(a[4]),
    .B(b[4]),
    .COUT(_11_),
    .SUM(_12_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _79_ (
    .A(a[6]),
    .B(b[6]),
    .COUT(_13_),
    .SUM(_14_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _80_ (
    .A(a[7]),
    .B(b[7]),
    .COUT(_16_),
    .SUM(_17_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _81_ (
    .A(a[0]),
    .B(b[0]),
    .COUT(_07_),
    .SUM(_45_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _82_ (
    .A(a[2]),
    .B(b[2]),
    .COUT(_18_),
    .SUM(_19_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _83_ (
    .A(a[5]),
    .B(b[5]),
    .COUT(_20_),
    .SUM(_21_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _84_ (
    .A(a[1]),
    .B(b[1]),
    .COUT(_22_),
    .SUM(_15_)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[0]$_DFF_PN0_  (
    .CLK(clk),
    .D(_45_),
    .Q(sum_out[0]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[1]$_DFF_PN0_  (
    .CLK(clk),
    .D(_46_),
    .Q(sum_out[1]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[2]$_DFF_PN0_  (
    .CLK(clk),
    .D(_01_),
    .Q(sum_out[2]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[3]$_DFF_PN0_  (
    .CLK(clk),
    .D(_02_),
    .Q(sum_out[3]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[4]$_DFF_PN0_  (
    .CLK(clk),
    .D(_03_),
    .Q(sum_out[4]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[5]$_DFF_PN0_  (
    .CLK(clk),
    .D(_04_),
    .Q(sum_out[5]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[6]$_DFF_PN0_  (
    .CLK(clk),
    .D(_05_),
    .Q(sum_out[6]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[7]$_DFF_PN0_  (
    .CLK(clk),
    .D(_06_),
    .Q(sum_out[7]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \sum_out[8]$_DFF_PN0_  (
    .CLK(clk),
    .D(_00_),
    .Q(sum_out[8]),
    .RESET_B(rst_n)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/sum_stage/design/src/sum_stage.v:13.5-21.8" *)
  sky130_fd_sc_hd__dfrtp_1 \valid$_DFF_PN0_  (
    .CLK(clk),
    .D(in_valid),
    .Q(valid),
    .RESET_B(rst_n)
  );
endmodule
