/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "fp16_multiplier" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fp16_multiplier/design/src/fp16_multiplier.v:4.1-14.10" *)
module fp16_multiplier(a, b, result);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fp16_multiplier/design/src/fp16_multiplier.v:5.18-5.19" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fp16_multiplier/design/src/fp16_multiplier.v:6.18-6.19" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fp16_multiplier/design/src/fp16_multiplier.v:7.23-7.29" *)
  output [15:0] result;
  wire [15:0] result;
  wire _00_;
  sky130_fd_sc_hd__conb_1 _01_ (
    .LO(_00_)
  );
  sky130_fd_sc_hd__buf_4 _02_ (
    .A(_00_),
    .X(result[0])
  );
  sky130_fd_sc_hd__buf_4 _03_ (
    .A(_00_),
    .X(result[1])
  );
  sky130_fd_sc_hd__buf_4 _04_ (
    .A(_00_),
    .X(result[2])
  );
  sky130_fd_sc_hd__buf_4 _05_ (
    .A(_00_),
    .X(result[3])
  );
  sky130_fd_sc_hd__buf_4 _06_ (
    .A(_00_),
    .X(result[4])
  );
  sky130_fd_sc_hd__buf_4 _07_ (
    .A(_00_),
    .X(result[5])
  );
  sky130_fd_sc_hd__buf_4 _08_ (
    .A(_00_),
    .X(result[6])
  );
  sky130_fd_sc_hd__buf_4 _09_ (
    .A(_00_),
    .X(result[7])
  );
  sky130_fd_sc_hd__buf_4 _10_ (
    .A(_00_),
    .X(result[8])
  );
  sky130_fd_sc_hd__buf_4 _11_ (
    .A(_00_),
    .X(result[9])
  );
  sky130_fd_sc_hd__buf_4 _12_ (
    .A(_00_),
    .X(result[10])
  );
  sky130_fd_sc_hd__buf_4 _13_ (
    .A(_00_),
    .X(result[11])
  );
  sky130_fd_sc_hd__buf_4 _14_ (
    .A(_00_),
    .X(result[12])
  );
  sky130_fd_sc_hd__buf_4 _15_ (
    .A(_00_),
    .X(result[13])
  );
  sky130_fd_sc_hd__buf_4 _16_ (
    .A(_00_),
    .X(result[14])
  );
  sky130_fd_sc_hd__buf_4 _17_ (
    .A(_00_),
    .X(result[15])
  );
endmodule
