from __future__ import annotations

from spec2rtl.expr import render_expr
from spec2rtl.ir import (
    AssignmentIR,
    CombBehaviorIR,
    FSMOutputIR,
    GeneratedTestbench,
    IfIR,
    ModuleIR,
    PortIR,
    RenderStrategy,
    VerificationEvidenceIR,
)


def render_verilog(ir: ModuleIR, strategy: RenderStrategy) -> str:
    lines: list[str] = []
    if strategy.include_header_comments:
        lines.append("// Generated by Spec-to-RTL pipeline: grammar -> IR -> RTL")
        for note in ir.notes:
            for note_line in str(note).splitlines():
                lines.append(f"// {note_line}")
        lines.append("")

    lines.append(f"module {ir.name} (")
    lines.extend(_render_port_block(ir, strategy))
    lines.append(");")
    lines.append("")
    lines.extend(_render_internal_declarations(ir, strategy))

    if ir.processes:
        lines.extend(_render_processes(ir))
    elif ir.design_kind == "counter" and ir.counter:
        lines.extend(_render_counter(ir, strategy))
    elif ir.design_kind == "register" and ir.register:
        lines.extend(_render_register(ir, strategy))
    elif ir.design_kind == "shift_register" and ir.shift_register:
        lines.extend(_render_shift_register(ir, strategy))
    elif ir.design_kind == "combinational" and ir.combinational:
        lines.extend(_render_combinational(ir, strategy))
    elif ir.design_kind == "fsm" and ir.fsm:
        lines.extend(_render_fsm(ir, strategy))
    else:
        lines.extend(_render_generic(ir, strategy))

    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def render_testbench(ir: ModuleIR) -> GeneratedTestbench:
    if not ir.verification.enable_tb:
        return GeneratedTestbench(text=None, evidence=VerificationEvidenceIR(tb_kind="none", achieved_level="none"))
    if ir.verification.seq_steps:
        return _render_seq_steps_tb(ir)
    if ir.verification.comb_vectors:
        return _render_comb_vectors_tb(ir)
    if ir.design_kind == "counter" and ir.counter:
        return GeneratedTestbench(
            text=_render_counter_tb(ir),
            evidence=VerificationEvidenceIR(
                tb_kind="counter_functional",
                achieved_level="functional",
                oracle_independent=True,
                covered_checks=["reset behavior", "count increment", "count hold"],
            ),
        )
    if ir.design_kind == "register" and ir.register:
        return GeneratedTestbench(
            text=_render_register_tb(ir),
            evidence=VerificationEvidenceIR(
                tb_kind="register_functional",
                achieved_level="functional",
                oracle_independent=True,
                covered_checks=["reset behavior", "single load", "hold when disabled"],
            ),
        )
    if ir.design_kind == "shift_register" and ir.shift_register:
        return GeneratedTestbench(
            text=_render_shift_register_tb(ir),
            evidence=VerificationEvidenceIR(
                tb_kind="shift_register_functional",
                achieved_level="functional",
                oracle_independent=True,
                covered_checks=["reset behavior", "shift behavior", "hold when disabled"],
            ),
        )
    if ir.design_kind == "fsm" and ir.fsm:
        return _render_fsm_tb(ir)
    if ir.design_kind == "combinational" and ir.combinational:
        return _render_combinational_tb(ir)
    return GeneratedTestbench(
        text=_render_smoke_tb(ir),
        evidence=VerificationEvidenceIR(
            tb_kind="generic_smoke",
            achieved_level="smoke",
            oracle_independent=False,
            limitations=["no independent functional oracle for this design kind"],
        ),
    )


def _render_port_block(ir: ModuleIR, strategy: RenderStrategy) -> list[str]:
    items: list[str] = []
    for idx, port in enumerate(ir.ports):
        suffix = "," if idx < len(ir.ports) - 1 else ""
        items.append(f"    {_port_decl(port, ir, strategy)}{suffix}")
    return items


def _render_internal_declarations(ir: ModuleIR, strategy: RenderStrategy) -> list[str]:
    lines: list[str] = []
    for signal in ir.signals:
        lines.append(f"    {signal.kind} {_verilog_range(signal.width)}{signal.name};")
    if strategy.internalize_outputs:
        for port in ir.ports:
            if port.direction == "output":
                lines.append(f"    reg {_verilog_range(port.width)}{port.name}_r;")
                lines.append(f"    assign {port.name} = {port.name}_r;")
    if lines:
        lines.append("")
    return lines


def _render_processes(ir: ModuleIR) -> list[str]:
    lines: list[str] = []
    for process in ir.processes:
        if process.kind == "comb":
            lines.append("    always @* begin")
            lines.extend(_render_statements(ir, process.body, indent="        ", blocking=True))
            lines.append("    end")
            lines.append("")
            continue

        clk = process.clock or ir.clock or "clk"
        reset = process.reset or ir.reset
        if reset:
            sensitivity = f"posedge {clk} or {'negedge' if reset.active_low else 'posedge'} {reset.signal}"
            cond = f"!{reset.signal}" if reset.active_low else reset.signal
            lines.append(f"    always @({sensitivity}) begin")
            lines.append(f"        if ({cond}) begin")
            lines.extend(_render_statements(ir, process.reset_body, indent="            ", blocking=False))
            lines.append("        end else begin")
            lines.extend(_render_statements(ir, process.body, indent="            ", blocking=False))
            lines.append("        end")
            lines.append("    end")
            lines.append("")
        else:
            lines.append(f"    always @(posedge {clk}) begin")
            lines.extend(_render_statements(ir, process.body, indent="        ", blocking=False))
            lines.append("    end")
            lines.append("")
    return lines


def _render_statements(ir: ModuleIR, statements: list[AssignmentIR | IfIR], indent: str, blocking: bool) -> list[str]:
    lines: list[str] = []
    for statement in statements:
        if isinstance(statement, AssignmentIR):
            op = "=" if blocking or statement.blocking else "<="
            lines.append(f"{indent}{statement.target} {op} {_forced_expr(ir, statement.target, statement.expr)};")
            continue
        lines.append(f"{indent}if ({render_expr(statement.condition)}) begin")
        lines.extend(_render_statements(ir, statement.then_body, indent + "    ", blocking))
        if statement.else_body:
            lines.append(f"{indent}end else begin")
            lines.extend(_render_statements(ir, statement.else_body, indent + "    ", blocking))
        lines.append(f"{indent}end")
    return lines


def _render_counter(ir: ModuleIR, strategy: RenderStrategy) -> list[str]:
    counter = ir.counter
    assert counter is not None
    target = _target_name(counter.target, strategy)
    width = _signal_width(ir, counter.target)
    step = _literal(width, counter.step)
    max_value = _literal(width, (1 << width) - 1)
    reset_value = _literal(width, _state_reset(ir, counter.target))
    lines = _seq_header(ir)
    lines.append(f"            {target} <= {reset_value};")
    lines.append("        end else begin")
    if counter.enable:
        lines.append(f"            if ({counter.enable}) begin")
        if ir.repair_controls.counter_hold_when_enabled:
            lines.append(f"                {target} <= {target};")
        elif counter.direction == "down":
            if counter.wrap:
                lines.append(f"                {target} <= {target} - {step};")
            else:
                lines.append(f"                if ({target} != {_literal(width, 0)}) {target} <= {target} - {step};")
        else:
            if counter.wrap:
                lines.append(f"                {target} <= {target} + {step};")
            else:
                lines.append(f"                if ({target} != {max_value}) {target} <= {target} + {step};")
        lines.append("            end")
        if ir.repair_controls.counter_ignore_enable:
            op = "-" if counter.direction == "down" else "+"
            lines.append("            else begin")
            lines.append(f"                {target} <= {target} {op} {step};")
            lines.append("            end")
    else:
        op = "-" if counter.direction == "down" else "+"
        lines.append(f"            {target} <= {target} {op} {step};")
    lines.append("        end")
    lines.append("    end")
    lines.append("")
    return lines


def _render_register(ir: ModuleIR, strategy: RenderStrategy) -> list[str]:
    behavior = ir.register
    assert behavior is not None
    target = _target_name(behavior.target, strategy)
    reset_value = _literal(_signal_width(ir, behavior.target), _state_reset(ir, behavior.target))
    lines = _seq_header(ir)
    lines.append(f"            {target} <= {reset_value};")
    lines.append("        end else begin")
    if behavior.enable:
        lines.append(f"            if ({behavior.enable}) begin")
        if ir.repair_controls.register_hold_when_enabled:
            lines.append(f"                {target} <= {target};")
        else:
            lines.append(f"                {target} <= {behavior.data};")
        lines.append("            end")
        if ir.repair_controls.register_ignore_enable:
            lines.append("            else begin")
            lines.append(f"                {target} <= {behavior.data};")
            lines.append("            end")
        elif behavior.hold_value:
            lines.append("            else begin")
            lines.append(f"                {target} <= {behavior.hold_value};")
            lines.append("            end")
    else:
        lines.append(f"            {target} <= {behavior.data};")
    lines.append("        end")
    lines.append("    end")
    lines.append("")
    return lines


def _render_shift_register(ir: ModuleIR, strategy: RenderStrategy) -> list[str]:
    behavior = ir.shift_register
    assert behavior is not None
    target = _target_name(behavior.target, strategy)
    width = _signal_width(ir, behavior.target)
    reset_value = _literal(width, _state_reset(ir, behavior.target))
    lines = _seq_header(ir)
    lines.append(f"            {target} <= {reset_value};")
    lines.append("        end else begin")
    effective_direction = behavior.direction
    if ir.repair_controls.shift_reverse_direction:
        effective_direction = "left" if behavior.direction == "right" else "right"
    if behavior.enable:
        lines.append(f"            if ({behavior.enable}) begin")
    if effective_direction == "right":
        lines.append(f"                {target} <= {{{behavior.serial_in}, {target}[{width - 1}:1]}};")
    elif width > 1:
        lines.append(f"                {target} <= {{{target}[{width - 2}:0], {behavior.serial_in}}};")
    else:
        lines.append(f"                {target} <= {behavior.serial_in};")
    if behavior.serial_out:
        lines.append(f"                {behavior.serial_out} <= {target}[{0 if effective_direction == 'right' else width - 1}];")
    if behavior.enable:
        lines.append("            end")
        if ir.repair_controls.shift_ignore_enable:
            lines.append("            else begin")
            if effective_direction == "right":
                lines.append(f"                {target} <= {{{behavior.serial_in}, {target}[{width - 1}:1]}};")
            elif width > 1:
                lines.append(f"                {target} <= {{{target}[{width - 2}:0], {behavior.serial_in}}};")
            else:
                lines.append(f"                {target} <= {behavior.serial_in};")
            lines.append("            end")
    lines.append("        end")
    lines.append("    end")
    lines.append("")
    return lines


def _render_combinational(ir: ModuleIR, strategy: RenderStrategy) -> list[str]:
    lines = ["    always @* begin"]
    for operation in ir.combinational:
        target = _target_name(operation.target, strategy)
        expr = _literal(_signal_width(ir, operation.target), 0) if _force_zero(ir, operation.target) else _comb_expr(operation)
        lines.append(f"        {target} = {expr};")
    lines.append("    end")
    lines.append("")
    return lines


def _render_fsm(ir: ModuleIR, strategy: RenderStrategy) -> list[str]:
    fsm = ir.fsm
    assert fsm is not None
    width = max(1, (len(fsm.states) - 1).bit_length())
    lines: list[str] = []
    for index, state in enumerate(fsm.states):
        lines.append(f"    localparam [{width - 1}:0] {state} = {width}'d{index};")
    lines.append(f"    reg [{width - 1}:0] {fsm.state_signal};")
    lines.append(f"    reg [{width - 1}:0] next_{fsm.state_signal};")
    lines.append("")
    lines.extend(_seq_header(ir, state_signal=fsm.state_signal, reset_state=fsm.reset_state))
    lines.append("        end else begin")
    lines.append(f"            {fsm.state_signal} <= next_{fsm.state_signal};")
    lines.append("        end")
    lines.append("    end")
    lines.append("")
    lines.append("    always @* begin")
    lines.append(f"        next_{fsm.state_signal} = {fsm.state_signal};")
    for port in ir.ports:
        if port.direction == "output":
            lines.append(f"        {_target_name(port.name, strategy)} = {_literal(port.width, 0)};")
    lines.append(f"        case ({fsm.state_signal})")
    for state in fsm.states:
        lines.append(f"            {state}: begin")
        output_behavior = next((item for item in fsm.outputs if item.state == state), None)
        if output_behavior:
            for target, expr in output_behavior.assignments.items():
                rendered_expr = _literal(_signal_width(ir, target), 0) if _force_zero(ir, target) else expr
                lines.append(f"                {_target_name(target, strategy)} = {rendered_expr};")
        transitions = [item for item in fsm.transitions if item.src == state]
        if transitions:
            for transition in transitions:
                if ir.repair_controls.fsm_force_self_loop:
                    lines.append(f"                next_{fsm.state_signal} = {fsm.state_signal};")
                elif transition.condition:
                    lines.append(f"                if ({transition.condition}) next_{fsm.state_signal} = {transition.dst};")
                else:
                    lines.append(f"                next_{fsm.state_signal} = {transition.dst};")
        else:
            lines.append(f"                next_{fsm.state_signal} = {fsm.state_signal};")
        lines.append("            end")
    lines.append("            default: begin")
    lines.append(f"                next_{fsm.state_signal} = {fsm.reset_state};")
    lines.append("            end")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("")
    return lines


def _render_generic(ir: ModuleIR, strategy: RenderStrategy) -> list[str]:
    if ir.clock:
        lines = _seq_header(ir)
        for port in ir.ports:
            if port.direction == "output":
                lines.append(f"            {_target_name(port.name, strategy)} <= {_forced_or_default_literal(ir, port.name, port.width)};")
        lines.append("        end else begin")
        lines.append("            // TODO: lower richer grammar rules into sequential behavior.")
        lines.append("        end")
        lines.append("    end")
        lines.append("")
        return lines
    lines = ["    always @* begin"]
    for port in ir.ports:
        if port.direction == "output":
            lines.append(f"        {_target_name(port.name, strategy)} = {_forced_or_default_literal(ir, port.name, port.width)};")
    lines.append("    end")
    lines.append("")
    return lines


def _seq_header(ir: ModuleIR, state_signal: str | None = None, reset_state: str | None = None) -> list[str]:
    clk = ir.clock or "clk"
    if ir.reset:
        sensitivity = f"posedge {clk} or {'negedge' if ir.reset.active_low else 'posedge'} {ir.reset.signal}"
        cond = f"!{ir.reset.signal}" if ir.reset.active_low else ir.reset.signal
        lines = [f"    always @({sensitivity}) begin", f"        if ({cond}) begin"]
        if state_signal and reset_state:
            lines.append(f"            {state_signal} <= {reset_state};")
        return lines
    return [f"    always @(posedge {clk}) begin", "        begin"]


def _render_counter_tb(ir: ModuleIR) -> str:
    counter = ir.counter
    assert counter is not None
    width = _signal_width(ir, counter.target)
    clk = ir.clock or "clk"
    rst = ir.reset.signal if ir.reset else "rst"
    rst_asserted = "1'b0" if ir.reset and ir.reset.active_low else "1'b1"
    rst_deasserted = "1'b1" if ir.reset and ir.reset.active_low else "1'b0"
    lines = ["`timescale 1ns/1ps", "", f"module tb_{ir.name};"]
    for port in ir.ports:
        decl = "reg" if port.direction == "input" else "wire"
        lines.append(f"    {decl} {_verilog_range(port.width)}{port.name};")
    lines.extend(
        [
            "",
            f"    {ir.name} dut (",
            ",\n".join(f"        .{port.name}({port.name})" for port in ir.ports),
            "    );",
            "",
            f"    always #5 {clk} = ~{clk};",
            "",
            "    initial begin",
            f"        {clk} = 1'b0;",
            f"        {rst} = {rst_asserted};",
        ]
    )
    if counter.enable:
        lines.append(f"        {counter.enable} = 1'b0;")
    lines.extend(
        [
            "        #2;",
            f"        if ({counter.target} !== {_literal(width, 0)}) $fatal(1, \"reset failed\");",
            f"        {rst} = {rst_deasserted};",
        ]
    )
    if counter.enable:
        lines.append(f"        {counter.enable} = 1'b1;")
    lines.extend(
        [
            f"        repeat (3) @(posedge {clk});",
            f"        #1 if ({counter.target} !== {_literal(width, 3)}) $fatal(1, \"increment failed\");",
        ]
    )
    if counter.enable:
        lines.extend(
            [
                f"        {counter.enable} = 1'b0;",
                f"        @(posedge {clk});",
                f"        #1 if ({counter.target} !== {_literal(width, 3)}) $fatal(1, \"hold failed\");",
            ]
        )
    lines.extend([f"        $display(\"PASS tb_{ir.name}\");", "        $finish;", "    end", "endmodule", ""])
    return "\n".join(lines)


def _render_register_tb(ir: ModuleIR) -> str:
    behavior = ir.register
    assert behavior is not None
    width = _signal_width(ir, behavior.target)
    clk = ir.clock or "clk"
    rst = ir.reset.signal if ir.reset else "rst"
    rst_asserted = "1'b0" if ir.reset and ir.reset.active_low else "1'b1"
    rst_deasserted = "1'b1" if ir.reset and ir.reset.active_low else "1'b0"
    lines = ["`timescale 1ns/1ps", "", f"module tb_{ir.name};"]
    for port in ir.ports:
        decl = "reg" if port.direction == "input" else "wire"
        lines.append(f"    {decl} {_verilog_range(port.width)}{port.name};")
    lines.extend(
        [
            "",
            f"    {ir.name} dut (",
            ",\n".join(f"        .{port.name}({port.name})" for port in ir.ports),
            "    );",
            "",
            f"    always #5 {clk} = ~{clk};",
            "",
            "    initial begin",
            f"        {clk} = 1'b0;",
            f"        {rst} = {rst_asserted};",
        ]
    )
    if behavior.enable:
        lines.append(f"        {behavior.enable} = 1'b0;")
    lines.extend(
        [
            f"        {behavior.data} = {_literal(width, 0)};",
            "        #2;",
            f"        if ({behavior.target} !== {_literal(width, 0)}) $fatal(1, \"reset failed\");",
            f"        {rst} = {rst_deasserted};",
            f"        {behavior.data} = {_literal(width, 10)};",
        ]
    )
    if behavior.enable:
        lines.append(f"        {behavior.enable} = 1'b1;")
    lines.extend(
        [
            f"        @(posedge {clk});",
            f"        #1 if ({behavior.target} !== {_literal(width, 10)}) $fatal(1, \"load failed\");",
        ]
    )
    if behavior.enable:
        lines.extend(
            [
                f"        {behavior.enable} = 1'b0;",
                f"        {behavior.data} = {_literal(width, 3)};",
                f"        @(posedge {clk});",
                f"        #1 if ({behavior.target} !== {_literal(width, 10)}) $fatal(1, \"hold failed\");",
            ]
        )
    lines.extend([f"        $display(\"PASS tb_{ir.name}\");", "        $finish;", "    end", "endmodule", ""])
    return "\n".join(lines)


def _render_shift_register_tb(ir: ModuleIR) -> str:
    behavior = ir.shift_register
    assert behavior is not None
    width = _signal_width(ir, behavior.target)
    clk = ir.clock or "clk"
    rst = ir.reset.signal if ir.reset else "rst"
    rst_asserted = "1'b0" if ir.reset and ir.reset.active_low else "1'b1"
    rst_deasserted = "1'b1" if ir.reset and ir.reset.active_low else "1'b0"
    first_value = _literal(width, 1 if behavior.direction == "left" else 1 << max(width - 1, 0))
    second_value = _literal(width, 2 if behavior.direction == "left" and width > 1 else (1 << max(width - 2, 0) if behavior.direction == "right" and width > 1 else 0))
    lines = ["`timescale 1ns/1ps", "", f"module tb_{ir.name};"]
    for port in ir.ports:
        decl = "reg" if port.direction == "input" else "wire"
        lines.append(f"    {decl} {_verilog_range(port.width)}{port.name};")
    lines.extend(
        [
            "",
            f"    {ir.name} dut (",
            ",\n".join(f"        .{port.name}({port.name})" for port in ir.ports),
            "    );",
            "",
            f"    always #5 {clk} = ~{clk};",
            "",
            "    initial begin",
            f"        {clk} = 1'b0;",
            f"        {rst} = {rst_asserted};",
            f"        {behavior.serial_in} = 1'b0;",
        ]
    )
    if behavior.enable:
        lines.append(f"        {behavior.enable} = 1'b0;")
    lines.extend(
        [
            "        #2;",
            f"        if ({behavior.target} !== {_literal(width, 0)}) $fatal(1, \"reset failed\");",
            f"        {rst} = {rst_deasserted};",
        ]
    )
    if behavior.enable:
        lines.append(f"        {behavior.enable} = 1'b1;")
    lines.extend(
        [
            f"        {behavior.serial_in} = 1'b1;",
            f"        @(posedge {clk});",
            f"        #1 if ({behavior.target} !== {first_value}) $fatal(1, \"shift failed\");",
            f"        {behavior.serial_in} = 1'b0;",
            f"        @(posedge {clk});",
            f"        #1 if ({behavior.target} !== {second_value}) $fatal(1, \"shift failed\");",
        ]
    )
    if behavior.enable:
        lines.extend(
            [
                f"        {behavior.enable} = 1'b0;",
                f"        {behavior.serial_in} = 1'b1;",
                f"        @(posedge {clk});",
                f"        #1 if ({behavior.target} !== {second_value}) $fatal(1, \"hold failed\");",
            ]
        )
    lines.extend([f"        $display(\"PASS tb_{ir.name}\");", "        $finish;", "    end", "endmodule", ""])
    return "\n".join(lines)


def _render_smoke_tb(ir: ModuleIR) -> str:
    lines = ["`timescale 1ns/1ps", "", f"module tb_{ir.name};"]
    for port in ir.ports:
        decl = "reg" if port.direction == "input" else "wire"
        lines.append(f"    {decl} {_verilog_range(port.width)}{port.name};")
    lines.extend(
        [
            "",
            f"    {ir.name} dut (",
            ",\n".join(f"        .{port.name}({port.name})" for port in ir.ports),
            "    );",
            "",
            "    initial begin",
        ]
    )
    for port in ir.ports:
        if port.direction == "input":
            lines.append(f"        {port.name} = {_literal(port.width, 0)};")
    lines.extend(["        #10;", f"        $display(\"PASS tb_{ir.name}\");", "        $finish;", "    end", "endmodule", ""])
    return "\n".join(lines)


def _render_fsm_tb(ir: ModuleIR) -> GeneratedTestbench:
    fsm = ir.fsm
    assert fsm is not None
    output_ports = [port for port in ir.ports if port.direction == "output"]
    unsupported = [item.condition for item in fsm.transitions if item.condition and item.condition not in {port.name for port in ir.ports if port.direction == "input"}]
    if unsupported:
        return GeneratedTestbench(
            text=_render_smoke_tb(ir),
            evidence=VerificationEvidenceIR(
                tb_kind="fsm_smoke",
                achieved_level="smoke",
                oracle_independent=True,
                limitations=[f"unsupported FSM transition conditions for directed checking: {', '.join(unsupported)}"],
            ),
        )

    clk = ir.clock or "clk"
    rst = ir.reset.signal if ir.reset else "rst"
    rst_asserted = "1'b0" if ir.reset and ir.reset.active_low else "1'b1"
    rst_deasserted = "1'b1" if ir.reset and ir.reset.active_low else "1'b0"
    state_width = max(1, (len(fsm.states) - 1).bit_length())
    lines = ["`timescale 1ns/1ps", "", f"module tb_{ir.name};"]
    for port in ir.ports:
        decl = "reg" if port.direction == "input" else "wire"
        lines.append(f"    {decl} {_verilog_range(port.width)}{port.name};")
    for index, state in enumerate(fsm.states):
        lines.append(f"    localparam [{state_width - 1}:0] {state} = {state_width}'d{index};")
    lines.extend(["", f"    {ir.name} dut (", ",\n".join(f"        .{port.name}({port.name})" for port in ir.ports), "    );", "", f"    always #5 {clk} = ~{clk};", ""])
    for output in output_ports:
        lines.append(f"    reg {_verilog_range(output.width)}expected_{output.name};")
    lines.extend(
        [
            "    task check_state_outputs;",
            "        input [255:0] step_name;",
            "        input integer expected_state;",
            "        begin",
            f"            if (dut.{fsm.state_signal} !== expected_state) begin",
            f"                $display(\"FAIL %0s: expected state=%0d got=%0d\", step_name, expected_state, dut.{fsm.state_signal});",
            "                $fatal(1);",
            "            end",
        ]
    )
    for output in output_ports:
        lines.append(f"            if ({output.name} !== expected_{output.name}) begin")
        lines.append(f"                $display(\"FAIL %0s: expected {output.name}=%b got %b\", step_name, expected_{output.name}, {output.name});")
        lines.append("                $fatal(1);")
        lines.append("            end")
    lines.extend(["        end", "    endtask", ""])

    lines.extend(["    initial begin", f"        {clk} = 1'b0;", f"        {rst} = {rst_asserted};"])
    for port in ir.ports:
        if port.direction == "input" and port.name not in {clk, rst}:
            lines.append(f"        {port.name} = {_literal(port.width, 0)};")
    _emit_expected_output_assignments(lines, output_ports, _fsm_output_for_state(fsm.outputs, fsm.reset_state))
    lines.extend(["        #1;", f"        check_state_outputs(\"reset\", {fsm.reset_state});", f"        {rst} = {rst_deasserted};"])

    covered = ["reset behavior"]
    for transition in fsm.transitions:
        state_label = transition.src.lower()
        if transition.condition and transition.expect_hold_when_false:
            lines.append(f"        {transition.condition} = 1'b0;")
            _emit_expected_output_assignments(lines, output_ports, _fsm_output_for_state(fsm.outputs, transition.src))
            lines.append(f"        @(posedge {clk});")
            lines.append(f"        #1 check_state_outputs(\"hold_{state_label}\", {transition.src});")
            covered.append(f"hold in {transition.src} when {transition.condition}=0")
        if transition.condition:
            lines.append(f"        {transition.condition} = 1'b1;")
        _emit_expected_output_assignments(lines, output_ports, _fsm_output_for_state(fsm.outputs, transition.dst))
        lines.append(f"        @(posedge {clk});")
        lines.append(f"        #1 check_state_outputs(\"transition_{transition.src}_to_{transition.dst}\", {transition.dst});")
        covered.append(f"transition {transition.src}->{transition.dst}")
        if transition.condition:
            lines.append(f"        {transition.condition} = 1'b0;")

    lines.extend([f"        $display(\"PASS tb_{ir.name}\");", "        $finish;", "    end", "endmodule", ""])
    return GeneratedTestbench(
        text="\n".join(lines),
        evidence=VerificationEvidenceIR(
            tb_kind="fsm_functional",
            achieved_level="functional",
            oracle_independent=True,
            covered_checks=covered + [f"outputs in state {state.state}" for state in fsm.outputs],
        ),
    )


def _render_combinational_tb(ir: ModuleIR) -> GeneratedTestbench:
    if not all(_oracle_supported(operation) for operation in ir.combinational):
        return GeneratedTestbench(
            text=_render_smoke_tb(ir),
            evidence=VerificationEvidenceIR(
                tb_kind="combinational_smoke",
                achieved_level="smoke",
                oracle_independent=False,
                limitations=["no independent oracle available for one or more combinational operations"],
            ),
        )
    lines = ["`timescale 1ns/1ps", "", f"module tb_{ir.name};"]
    inputs = [port for port in ir.ports if port.direction == "input"]
    outputs = [port for port in ir.ports if port.direction == "output"]
    for port in inputs:
        lines.append(f"    reg {_verilog_range(port.width)}{port.name};")
    for port in outputs:
        lines.append(f"    wire {_verilog_range(port.width)}{port.name};")
        lines.append(f"    reg {_verilog_range(port.width)}expected_{port.name};")
    lines.extend(["", f"    {ir.name} dut (", ",\n".join(f"        .{port.name}({port.name})" for port in ir.ports), "    );", "", "    task check_outputs;", "        input [255:0] vector_name;", "        begin"])
    for port in outputs:
        lines.append(f"            if ({port.name} !== expected_{port.name}) begin")
        lines.append(f"                $display(\"FAIL %0s: expected {port.name}=%b got %b\", vector_name, expected_{port.name}, {port.name});")
        lines.append("                $fatal(1);")
        lines.append("            end")
    lines.extend(["        end", "    endtask", "", "    initial begin"])
    for port in inputs:
        lines.append(f"        {port.name} = {_literal(port.width, 0)};")

    for vector_name, assignments in _combinational_vectors(ir):
        for name, value in assignments.items():
            lines.append(f"        {name} = {value};")
        lines.extend(_comb_expected_assignments(ir.combinational))
        lines.append(f"        #1 check_outputs(\"{vector_name}\");")
    lines.extend([f"        $display(\"PASS tb_{ir.name}\");", "        $finish;", "    end", "endmodule", ""])
    vector_note = "exhaustive truth-table vectors" if _is_exhaustive_boolean(ir) else "directed input vectors"
    return GeneratedTestbench(
        text="\n".join(lines),
        evidence=VerificationEvidenceIR(
            tb_kind="combinational_functional",
            achieved_level="functional",
            oracle_independent=True,
            covered_checks=[vector_note, "independent oracle expected-value checks"],
        ),
    )


def _render_comb_vectors_tb(ir: ModuleIR) -> GeneratedTestbench:
    lines = ["`timescale 1ns/1ps", "", f"module tb_{ir.name};"]
    inputs = [port for port in ir.ports if port.direction == "input"]
    outputs = [port for port in ir.ports if port.direction == "output"]
    for port in inputs:
        lines.append(f"    reg {_verilog_range(port.width)}{port.name};")
    for port in outputs:
        lines.append(f"    wire {_verilog_range(port.width)}{port.name};")
        lines.append(f"    reg {_verilog_range(port.width)}expected_{port.name};")
    lines.extend(["", f"    {ir.name} dut (", ",\n".join(f"        .{port.name}({port.name})" for port in ir.ports), "    );", "", "    task check_outputs;", "        input [255:0] vector_name;", "        begin"])
    for port in outputs:
        lines.append(f"            if ({port.name} !== expected_{port.name}) begin")
        lines.append(f"                $display(\"FAIL %0s: expected {port.name}=%b got %b\", vector_name, expected_{port.name}, {port.name});")
        lines.append("                $fatal(1);")
        lines.append("            end")
    lines.extend(["        end", "    endtask", "", "    initial begin"])
    for port in inputs:
        lines.append(f"        {port.name} = {_literal(port.width, 0)};")
    for vector in ir.verification.comb_vectors:
        for name, expr in vector.drive.items():
            lines.append(f"        {name} = {render_expr(expr)};")
        for target, expr in vector.expect.items():
            lines.append(f"        expected_{target} = {render_expr(expr)};")
        lines.append(f"        #1 check_outputs(\"{vector.name}\");")
    lines.extend([f"        $display(\"PASS tb_{ir.name}\");", "        $finish;", "    end", "endmodule", ""])
    return GeneratedTestbench(
        text="\n".join(lines),
        evidence=VerificationEvidenceIR(
            tb_kind="verification_vectors_functional",
            achieved_level="functional",
            oracle_independent=True,
            covered_checks=[f"user vector {item.name}" for item in ir.verification.comb_vectors],
        ),
    )


def _render_seq_steps_tb(ir: ModuleIR) -> GeneratedTestbench:
    lines = ["`timescale 1ns/1ps", "", f"module tb_{ir.name};"]
    inputs = [port for port in ir.ports if port.direction == "input"]
    outputs = [port for port in ir.ports if port.direction == "output"]
    clk = ir.clock or next((port.name for port in inputs if port.name == "clk"), None)
    for port in inputs:
        lines.append(f"    reg {_verilog_range(port.width)}{port.name};")
    for port in outputs:
        lines.append(f"    wire {_verilog_range(port.width)}{port.name};")
        lines.append(f"    reg {_verilog_range(port.width)}expected_{port.name};")
    lines.extend(["", f"    {ir.name} dut (", ",\n".join(f"        .{port.name}({port.name})" for port in ir.ports), "    );", ""])
    if clk:
        lines.extend([f"    always #5 {clk} = ~{clk};", ""])
    lines.extend(["    task check_outputs;", "        input [255:0] step_name;", "        begin"])
    for port in outputs:
        lines.append(f"            if ({port.name} !== expected_{port.name}) begin")
        lines.append(f"                $display(\"FAIL %0s: expected {port.name}=%b got %b\", step_name, expected_{port.name}, {port.name});")
        lines.append("                $fatal(1);")
        lines.append("            end")
    lines.extend(["        end", "    endtask", "", "    initial begin"])
    for port in inputs:
        lines.append(f"        {port.name} = {_literal(port.width, 0)};")
    for step in ir.verification.seq_steps:
        for name, expr in step.drive.items():
            lines.append(f"        {name} = {render_expr(expr)};")
        if step.delay is not None:
            lines.append(f"        #{step.delay};")
        elif step.edge:
            lines.append(f"        @({step.edge});")
        else:
            lines.append("        #1;")
        for target, expr in step.expect.items():
            lines.append(f"        expected_{target} = {render_expr(expr)};")
        if step.expect:
            lines.append(f"        #1 check_outputs(\"{step.name}\");")
    lines.extend([f"        $display(\"PASS tb_{ir.name}\");", "        $finish;", "    end", "endmodule", ""])
    return GeneratedTestbench(
        text="\n".join(lines),
        evidence=VerificationEvidenceIR(
            tb_kind="verification_steps_functional",
            achieved_level="functional",
            oracle_independent=True,
            covered_checks=[f"user sequence step {item.name}" for item in ir.verification.seq_steps],
        ),
    )


def _emit_expected_output_assignments(lines: list[str], outputs: list[PortIR], assignments: dict[str, str]) -> None:
    for output in outputs:
        lines.append(f"        expected_{output.name} = {assignments.get(output.name, _literal(output.width, 0))};")


def _fsm_output_for_state(outputs: list[FSMOutputIR], state: str) -> dict[str, str]:
    item = next((entry for entry in outputs if entry.state == state), None)
    return item.assignments if item else {}


def _comb_expr(operation: CombBehaviorIR) -> str:
    if operation.operator == "buf":
        return operation.operands[0]
    if operation.operator == "not":
        return f"~{operation.operands[0]}"
    if operation.operator == "and":
        return " & ".join(operation.operands)
    if operation.operator == "or":
        return " | ".join(operation.operands)
    if operation.operator == "xor":
        return " ^ ".join(operation.operands)
    if operation.operator == "add":
        return " + ".join(operation.operands)
    if operation.operator == "sub":
        return " - ".join(operation.operands)
    if operation.operator == "mux":
        false_value = operation.operands[0]
        true_value = operation.operands[1] if len(operation.operands) > 1 else operation.operands[0]
        return f"{operation.select} ? {true_value} : {false_value}"
    if operation.operator == "eq":
        return " == ".join(operation.operands)
    if operation.operator == "lt":
        return " < ".join(operation.operands)
    if operation.operator == "gt":
        return " > ".join(operation.operands)
    if operation.operator == "expr" and operation.expr is not None:
        return render_expr(operation.expr)
    return "1'b0"


def _comb_expected_assignments(operations: list[CombBehaviorIR]) -> list[str]:
    lines: list[str] = []
    for operation in operations:
        target = f"expected_{operation.target}"
        if operation.operator == "buf":
            lines.append(f"        {target} = {operation.operands[0]};")
        elif operation.operator == "not":
            lines.append(f"        {target} = ~{operation.operands[0]};")
        elif operation.operator == "and":
            lines.append(f"        {target} = {' & '.join(operation.operands)};")
        elif operation.operator == "or":
            lines.append(f"        {target} = {' | '.join(operation.operands)};")
        elif operation.operator == "xor":
            lines.append(f"        {target} = {' ^ '.join(operation.operands)};")
        elif operation.operator == "add":
            lines.append(f"        {target} = {' + '.join(operation.operands)};")
        elif operation.operator == "sub":
            lines.append(f"        {target} = {' - '.join(operation.operands)};")
        elif operation.operator == "mux":
            false_value = operation.operands[0]
            true_value = operation.operands[1] if len(operation.operands) > 1 else operation.operands[0]
            lines.append(f"        if ({operation.select}) {target} = {true_value}; else {target} = {false_value};")
        elif operation.operator == "eq":
            lines.append(f"        {target} = ({operation.operands[0]} == {operation.operands[1]});")
        elif operation.operator == "lt":
            lines.append(f"        {target} = ({operation.operands[0]} < {operation.operands[1]});")
        elif operation.operator == "gt":
            lines.append(f"        {target} = ({operation.operands[0]} > {operation.operands[1]});")
    return lines


def _oracle_supported(operation: CombBehaviorIR) -> bool:
    return operation.operator in {"buf", "not", "and", "or", "xor", "add", "sub", "mux", "eq", "lt", "gt"}


def _is_exhaustive_boolean(ir: ModuleIR) -> bool:
    inputs = [port for port in ir.ports if port.direction == "input"]
    return len(inputs) <= 4 and all(port.width == 1 for port in inputs)


def _combinational_vectors(ir: ModuleIR) -> list[tuple[str, dict[str, str]]]:
    inputs = [port for port in ir.ports if port.direction == "input"]
    if _is_exhaustive_boolean(ir):
        vectors = []
        for value in range(1 << len(inputs)):
            assignments: dict[str, str] = {}
            for index, port in enumerate(inputs):
                bit = (value >> (len(inputs) - index - 1)) & 1
                assignments[port.name] = f"1'b{bit}"
            vectors.append((f"vector_{value}", assignments))
        return vectors
    vectors = []
    zero = {port.name: _literal(port.width, 0) for port in inputs}
    vectors.append(("zeros", zero))
    ones = {port.name: _literal(port.width, (1 << port.width) - 1) for port in inputs}
    vectors.append(("ones", ones))
    for port in inputs:
        assignments = {item.name: _literal(item.width, 0) for item in inputs}
        assignments[port.name] = _literal(port.width, 1)
        vectors.append((f"{port.name}_hot", assignments))
    return vectors


def _port_decl(port: PortIR, ir: ModuleIR, strategy: RenderStrategy) -> str:
    width = _verilog_range(port.width)
    if port.direction == "output" and not strategy.internalize_outputs:
        return f"output reg {width}{port.name}".rstrip()
    return f"{port.direction} {width}{port.name}".rstrip()


def _verilog_range(width: int) -> str:
    return f"[{width - 1}:0] " if width > 1 else ""


def _target_name(name: str, strategy: RenderStrategy) -> str:
    return f"{name}_r" if strategy.internalize_outputs else name


def _signal_width(ir: ModuleIR, name: str) -> int:
    for signal in ir.signals:
        if signal.name == name:
            return signal.width
    for signal in ir.state:
        if signal.name == name:
            return signal.width
    for port in ir.ports:
        if port.name == name:
            return port.width
    return 1


def _state_reset(ir: ModuleIR, name: str) -> int:
    for signal in ir.state:
        if signal.name == name:
            return signal.reset_value
    return 0


def _literal(width: int, value: int) -> str:
    return f"{width}'d{value}"


def _force_zero(ir: ModuleIR, target: str) -> bool:
    return target in ir.repair_controls.zero_output_targets


def _forced_or_default_literal(ir: ModuleIR, target: str, width: int) -> str:
    if _force_zero(ir, target):
        return _literal(width, 0)
    return _literal(width, 0)


def _forced_expr(ir: ModuleIR, target: str, expr: object) -> str:
    if _force_zero(ir, target):
        return _literal(_signal_width(ir, target), 0)
    return render_expr(expr)  # type: ignore[arg-type]
