/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "comb_adder8" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/comb_adder8/design/src/comb_adder8.v:3.1-13.10" *)
module comb_adder8(a, b, y);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/comb_adder8/design/src/comb_adder8.v:4.17-4.18" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/comb_adder8/design/src/comb_adder8.v:5.17-5.18" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/comb_adder8/design/src/comb_adder8.v:6.22-6.23" *)
  output [7:0] y;
  wire [7:0] y;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:6.31-6.32" *)
  wire _00_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _01_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _02_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _03_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _04_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _05_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:6.25-6.26" *)
  wire _06_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _07_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _08_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _09_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _10_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _11_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.26-8.27" *)
  wire _12_;
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:8.29-8.30" *)
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  sky130_fd_sc_hd__xor2_1 _35_ (
    .A(a[7]),
    .B(b[7]),
    .X(_14_)
  );
  sky130_fd_sc_hd__a211oi_2 _36_ (
    .A1(_06_),
    .A2(_00_),
    .B1(_09_),
    .C1(_12_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__o21ai_1 _37_ (
    .A1(_13_),
    .A2(_12_),
    .B1(_08_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor2_1 _38_ (
    .A(_15_),
    .B(_16_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__nand2_1 _39_ (
    .A(_03_),
    .B(_05_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a21oi_1 _40_ (
    .A1(_11_),
    .A2(_07_),
    .B1(_10_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__a21oi_1 _41_ (
    .A1(_03_),
    .A2(_04_),
    .B1(_02_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _42_ (
    .A1(_18_),
    .A2(_19_),
    .B1(_20_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a41oi_2 _43_ (
    .A1(_03_),
    .A2(_05_),
    .A3(_11_),
    .A4(_17_),
    .B1(_21_),
    .Y(_22_)
  );
  sky130_fd_sc_hd__xnor2_1 _44_ (
    .A(_14_),
    .B(_22_),
    .Y(y[7])
  );
  sky130_fd_sc_hd__a21oi_1 _45_ (
    .A1(_13_),
    .A2(_01_),
    .B1(_12_),
    .Y(_23_)
  );
  sky130_fd_sc_hd__nand2_1 _46_ (
    .A(_11_),
    .B(_08_),
    .Y(_24_)
  );
  sky130_fd_sc_hd__inv_1 _47_ (
    .A(_10_),
    .Y(_25_)
  );
  sky130_fd_sc_hd__nand2_1 _48_ (
    .A(_11_),
    .B(_07_),
    .Y(_26_)
  );
  sky130_fd_sc_hd__o211ai_1 _49_ (
    .A1(_23_),
    .A2(_24_),
    .B1(_25_),
    .C1(_26_),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a21oi_1 _50_ (
    .A1(_05_),
    .A2(_27_),
    .B1(_04_),
    .Y(_28_)
  );
  sky130_fd_sc_hd__xnor2_1 _51_ (
    .A(_03_),
    .B(_28_),
    .Y(y[6])
  );
  sky130_fd_sc_hd__o21bai_1 _52_ (
    .A1(_15_),
    .A2(_16_),
    .B1_N(_07_),
    .Y(_29_)
  );
  sky130_fd_sc_hd__a21oi_1 _53_ (
    .A1(_11_),
    .A2(_29_),
    .B1(_10_),
    .Y(_30_)
  );
  sky130_fd_sc_hd__xnor2_1 _54_ (
    .A(_05_),
    .B(_30_),
    .Y(y[5])
  );
  sky130_fd_sc_hd__nor2b_1 _55_ (
    .A(_23_),
    .B_N(_08_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__nor2_1 _56_ (
    .A(_07_),
    .B(_31_),
    .Y(_32_)
  );
  sky130_fd_sc_hd__xnor2_1 _57_ (
    .A(_11_),
    .B(_32_),
    .Y(y[4])
  );
  sky130_fd_sc_hd__a21o_2 _58_ (
    .A1(_06_),
    .A2(_00_),
    .B1(_09_),
    .X(_33_)
  );
  sky130_fd_sc_hd__a211oi_1 _59_ (
    .A1(_13_),
    .A2(_33_),
    .B1(_08_),
    .C1(_12_),
    .Y(_34_)
  );
  sky130_fd_sc_hd__nor2_1 _60_ (
    .A(_17_),
    .B(_34_),
    .Y(y[3])
  );
  sky130_fd_sc_hd__xor2_1 _61_ (
    .A(_13_),
    .B(_01_),
    .X(y[2])
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:42.31-44.12" *)
  sky130_fd_sc_hd__fa_1 _62_ (
    .A(a[1]),
    .B(b[1]),
    .CIN(_00_),
    .COUT(_01_),
    .SUM(y[1])
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _63_ (
    .A(a[6]),
    .B(b[6]),
    .COUT(_02_),
    .SUM(_03_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _64_ (
    .A(a[5]),
    .B(b[5]),
    .COUT(_04_),
    .SUM(_05_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _65_ (
    .A(a[0]),
    .B(b[0]),
    .COUT(_00_),
    .SUM(y[0])
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _66_ (
    .A(a[3]),
    .B(b[3]),
    .COUT(_07_),
    .SUM(_08_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _67_ (
    .A(a[1]),
    .B(b[1]),
    .COUT(_09_),
    .SUM(_06_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _68_ (
    .A(a[4]),
    .B(b[4]),
    .COUT(_10_),
    .SUM(_11_)
  );
  (* module_not_derived = 32'b00000000000000000000000000000001 *)
  (* src = "/home/sudar762/OpenROAD-flow-scripts/flow/platforms/sky130hd/cells_adders_hd.v:18.33-22.14" *)
  sky130_fd_sc_hd__ha_1 _69_ (
    .A(a[2]),
    .B(b[2]),
    .COUT(_12_),
    .SUM(_13_)
  );
endmodule
