/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "fir_filter" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fir_filter/design/src/fir_filter.v:4.1-20.10" *)
module fir_filter(clk, rst, x_in, h, y_out);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fir_filter/design/src/fir_filter.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fir_filter/design/src/fir_filter.v:6.11-6.14" *)
  input rst;
  wire rst;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fir_filter/design/src/fir_filter.v:7.11-7.15" *)
  input x_in;
  wire x_in;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fir_filter/design/src/fir_filter.v:8.11-8.12" *)
  input h;
  wire h;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/fir_filter/design/src/fir_filter.v:9.16-9.21" *)
  output y_out;
  wire y_out;
  wire _0_;
  sky130_fd_sc_hd__conb_1 _1_ (
    .LO(_0_)
  );
  sky130_fd_sc_hd__buf_4 _2_ (
    .A(_0_),
    .X(y_out)
  );
endmodule
