/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "seq_detector_0011" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/seq_detector_0011/design/src/seq_detector_0011.v:4.1-19.10" *)
module seq_detector_0011(clk, reset, data_in, detected);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/seq_detector_0011/design/src/seq_detector_0011.v:5.11-5.14" *)
  input clk;
  wire clk;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/seq_detector_0011/design/src/seq_detector_0011.v:6.11-6.16" *)
  input reset;
  wire reset;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/seq_detector_0011/design/src/seq_detector_0011.v:7.11-7.18" *)
  input data_in;
  wire data_in;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/seq_detector_0011/design/src/seq_detector_0011.v:8.16-8.24" *)
  output detected;
  wire detected;
  wire _0_;
  sky130_fd_sc_hd__conb_1 _1_ (
    .LO(_0_)
  );
  sky130_fd_sc_hd__buf_4 _2_ (
    .A(_0_),
    .X(detected)
  );
endmodule
