/* Generated by Yosys 0.64 (git sha1 8449dd470, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) [the-openroad-project/yosys] */

(* hdlname = "pulse_latch" *)
(* top =  1  *)
(* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/pulse_latch/design/src/pulse_latch.v:3.1-18.10" *)
module pulse_latch(clk, rst_n, set_pulse, flag);
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/pulse_latch/design/src/pulse_latch.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/pulse_latch/design/src/pulse_latch.v:5.11-5.16" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/pulse_latch/design/src/pulse_latch.v:6.11-6.20" *)
  input set_pulse;
  wire set_pulse;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/pulse_latch/design/src/pulse_latch.v:7.16-7.20" *)
  output flag;
  wire flag;
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/pulse_latch/design/src/pulse_latch.v:10.5-16.8" *)
  wire _0_;
  sky130_fd_sc_hd__or2_1 _1_ (
    .A(flag),
    .B(set_pulse),
    .X(_0_)
  );
  (* src = "/home/sudar762/projects/spec-to-rtl-agent/build/flow/pulse_latch/design/src/pulse_latch.v:10.5-16.8" *)
  sky130_fd_sc_hd__dfrtp_1 \flag$_DFF_PN0_  (
    .CLK(clk),
    .D(_0_),
    .Q(flag),
    .RESET_B(rst_n)
  );
endmodule
