// Generated by Spec-to-RTL pipeline: grammar -> IR -> RTL
// Detects a binary sequence "0011" in the input stream.

module seq_detector_0011 (
    input clk,
    input reset,
    input data_in,
    output reg detected
);

    always @(posedge clk or posedge reset) begin
        if (reset) begin
            detected <= 1'd0;
        end else begin
            // TODO: lower richer grammar rules into sequential behavior.
        end
    end

endmodule
